### ISSUE TITLE
When using data how does this improve performance?

### ISSUE THREAD

**Issue by slakbal** [pixxet/laravel-partialcache#3]
Hi quick question, Laravel already creates a view cache on the file system and it is effective when not dynamically using data, and it will be the same with any dynamically content that requires data. Hence the question I'm not sure if there would be a huge performance improvement? Personally I think OpCache might give you even better improvement without the need for this. But I would love your feedback and background on this and if you have noticed big improvements?

Thanks!

**Comment by RamonSmit** [comment]
Simple answer, The data _is_ cached too. So effectively creating a static HTML output.

**Comment by omaratpxt** [comment]
laravel cache is just caching the rendering part of the templates php rendered files. this package allows you to cache the output of another view as static html.

usecase: imagine having a dropdown menu with many inherits in it. you will need to render the tree each time page is loaded. with laravel different caches you can cache the rendered template php file, the data coming from the db but still need that the framework go through all cached data to output a dropdown menu which never changes and is always the same unless the data is changed.

with this package you can cache the output as static html and invalidate based on the same logic when you invalidate the data coming from your controller. if new data is coming then cache is dumped in it's generated once.
